#!/bin/sh
# openbox/autostart - Autostarts for Openbox WM

# tint2
tint2 &

# power
xfce4-power-manager &

# pulseaudio
(sleep 1s && ~/.bin/pulseaudio-oneshot) &

# mpd
(sleep 2s && mpd) &

# mpdscribble
(sleep 3s && mpdscribble) &

# compton
(sleep 1s && compton) &

# xrandr
(sleep 2s && ~/.bin/xrandr-adjust) &

# fehbg
(sleep 4s && ~/.fehbg) &

# neap
(sleep 4s && neap) &

