#!/bin/bash
# This script automates the stowing of dotfiles in this repository.

# Define the files to stow
TXTDOTS=('arch' 'bin' 'git' 'htop' 'ncmpcpp' 'ranger' 'tmux' 'vim' 'zsh')
XDOTS=('compton' 'dunst' 'feh' 'i3' 'pentadactyl' 'sxiv' 'weston' 'xorg')
OBDOTS=('openbox')

link-files(){
for pkg in ${QUEUE[@]}; do
	stow -v -R $pkg
done
}

case $1 in
	-t) QUEUE=${TXTDOTS[@]} link-files ;;
	-x) QUEUE=${XDOTS[@]} link-files ;;
	-a) QUEUE="${TXTDOTS[@]} ${XDOTS[@]}" link-files ;;
	-o) QUEUE=${OBDOTS[@]} link-files ;;
	*)  cat <<EOU
Usage: ${0##*/} [option]
    -a - Install terminal + graphical files
    -t - Install terminal files only
    -x - Install graphical files only
    -o - Install Openbox-related files
EOU
esac
