#!/bin/sh
# TODO: We github now! We should be symlinking those things.
# Edit accordingly
WHERE="$HOME"

# Check if there is a .config folder, make one if needed
if [ ! -d "$WHERE/.config" ]; then
	mkdir -p "$WHERE/.config"
fi

FILES="zshenv zshrc.local vimrc conkyrc fehbg Xresources xinitrc config/compton.conf"
for dot in $FILES; do
	echo -e "\e[1;32m==>\e[0m Installing $dot"
	cp -u $dot $WHERE/.$dot
done

FOLDERS="bin i3 vim ncmpcpp config/cower config/openbox config/nitrogen config/ranger config/dunst"
for dot in $FOLDERS; do
	echo -e "\e[1;34m==>\e[0m Installing folder $dot"
	rsync -avz $dot/ $WHERE/.$dot
done
