#!/bin/sh
DOTLOC="$HOME/.dotfiles"
WHERE="$HOME"
BACKUP="$HOME/.old-dotfiles"

DOTS="zshenv zshrc.local vimrc tmux.conf \
		conkyrc fehbg Xresources xinitrc neaprc \
		config/compton.conf \
		bin vim ncmpcpp \
		config/cower config/ranger config/dunst config/htop \
		config/openbox config/tint2 \
		config/i3 \
		config/skippy-xd"

# Check if there is a .config folder at destination, make one if needed
if [ ! -d "$WHERE/.config" ]; then
	mkdir -p "$WHERE/.config"
fi

# Check if there is a backup folder (and a config folder on it), make one if needed
if [ ! -d "$BACKUP/config" ]; then
	mkdir -p "$BACKUP/config"
fi

for dot in $DOTS; do
	echo -e "\e[1;31m==>\e[0m Moving old $dot into $BACKUP"
	mv $WHERE/.$dot $BACKUP/$dot
	echo -e "\e[1;32m==>\e[0m Linking $dot into $WHERE"
	ln -sf $DOTLOC/$dot $WHERE/.$dot
done
