#!/bin/sh
# link-files: links dotfiles from a repo into a folder
# Originally written by Michael Smalley, kanged by Renan Guilherme

# --- Location
DOTLOC="$HOME/.dotfiles"

# --- Defitions
HEADLESS_DOTS="zshenv zshrc vimrc tmux.conf
	bin vim ncmpcpp
	config/git config/cower config/ranger config/htop"

GRAPHICAL_DOTS="conkyrc vimperatorrc Xresources xprofile xinitrc
	config/compton.conf config/weston.ini
	config/i3 config/xcolors config/dunst config/feh config/sxiv"

OPENBOX_DOTS="neaprc
	config/skippy-xd config/tint2 config/openbox"

_usage(){
	echo "Usage: $(basename "$0") [-h | -x]"
	echo "    -h: Install headless configuration files"
	echo "    -x: Install headless + graphical configuration files"
	echo "    -o: Install Openbox configuration files (only)"
}

_checkconfig(){
	if [ -e "$HOME/.config" ]; then
		echo "==> $HOME/.config exists"
	else
		echo "==> $HOME/.config does not exist, creating"
		mkdir -p "$HOME/.config"
	fi
}

_linkfiles(){
case "$1" in
	"headless") QUEUE=$HEADLESS_DOTS;;
	"graphical") QUEUE=$GRAPHICAL_DOTS;;
	"openbox") QUEUE=$OPENBOX_DOTS;;
esac

echo "==> Installing $1 configuration files"
for dot in $QUEUE; do
	echo -e "==> Processing $dot"
	echo -e "\e[1;31m ==> \e[0m removing existing on $HOME"
	rm -r "$HOME/.$dot"
	echo -e "\e[1;32m ==> \e[0m linking new file into $HOME"
	ln -sf "$DOTLOC/$dot" "$HOME/.$dot"
done
}

case "$1" in
	"-h") _checkconfig ; _linkfiles headless ;;
	"-x") _checkconfig ; _linkfiles headless ; _linkfiles graphical ;;
	"-o") _checkconfig ; _linkfiles openbox ;;
	   *) _usage ;;
esac

