#!/bin/sh
# ~/.xprofile - Scripts to run before starting X

# --- xinitrc.d - Starts basic daemons such as D-Bus or PulseAudio
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# --- LXPolkit
/usr/lib/lxpolkit/lxpolkit &

# --- Xresources
[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources

# --- urxvt daemon
urxvtd -q -f -o

# WM/DEs are not called on .xprofile. Use .xinitrc instead

