#!/bin/sh
# ~/.i3/autostart - i3 autostart script
# While you can autostart things using .i3/config, I thought it would be a better
# idea to use a specific file to do these things.

# Desktop Session - so dmenu-session knows who we are
export DESKTOP_SESSION='i3'

# LXPolkit - A light polkit implementation
/usr/lib/lxpolkit/lxpolkit &

# GNOME Keyring - For NetworkManager, possibly others
gnome-keyring-daemon --start --components=secrets &

# Dropbox - File sync
dropboxd &

# NetworkManager - Pretty menus for wi-fi
nm-applet &

# xfce4-power-manager - Brightness keys and things like that
xfce4-power-manager &

# Clipit - Clipboard manager
clipit &

# Compton - standalone X compositor (vsync, shadows)
compton &

# MPD - Music Player Daemon
mpd &

# PulseAudio Oneshooter - Starts PulseAudio and friends
~/.bin/pulseaudio-oneshot &

# XRandR Adjuster - Set up dual monitors
(sleep 2s && ~/.bin/xrandr-adjust) &

# fehbg - Wallpaper
(sleep 4s && ~/.fehbg) &

