#!/bin/sh
# openbox/autostart - Applications to run along with Openbox

# LXPolkit - A light polkit implementation
# I think this is a system-wide autostart though
#/usr/lib/lxpolkit/lxpolkit &

# GNOME Keyring - For NetworkManager, possibly others
gnome-keyring-daemon --start --components=secrets &

# Dropbox - File sync
dropboxd &

# NetworkManager - Pretty menus for wi-fi
nm-applet &

# xfce4-power-manager - Brightness keys and things like that
xfce4-power-manager &

# Compton - standalone X compositor (vsync, shadows)
compton &

# MPD - Music Player Daemon
mpd &

# PulseAudio Oneshooter - Starts PulseAudio and friends
~/.bin/pulseaudio-oneshot &

# XRandR Adjuster - Set up dual monitors
~/.bin/xrandr-adjust &

# fehbg
~/.fehbg &

# Tint2
tint2 &

