#!/bin/sh
# openbox/autostart - Autostarts for Openbox WM

# tint2
tint2 &

# power
xfce4-power-manager &

# neap
neap &

# compton
compton &

# pulseaudio
( pidof pulseaudio ) || start-pulseaudio-x11 &

# xfce4-volumed
(sleep 2s && xfce4-volumed-pulse ) &

# pnmixer
(sleep 2s && pnmixer ) &

# xrandr
( sleep 1s && ~/.bin/xrandr-adjust ) &

# fehbg
( sleep 3s && ~/.fehbg ) &
