#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/image-info
# Called by sxiv(1) whenever an image gets loaded.
# The output is displayed in sxiv's status bar.
# Arguments:
#   $1: path to image file
#   $2: image width
#   $3: image height

### Show the contents of clipboard if the file is from qrclip
if [[ "$1" == "/tmp/qr.png" ]]; then
	echo "$(xclip -o -sel clip)"
	exit
fi

### Default status bar generator
s=" | " # field separator

filename=$(basename -- "$1")
filesize=$(du -Hh -- "$1" | cut -f 1)

geometry="${2}x${3}"

echo "${filesize}${s}${geometry}${s}${filename}"

