#!/bin/sh

FREQ=$(nvidia-smi --query-gpu=clocks.current.graphics --format=csv,noheader,nounits)
TEMP=$(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits)

printf "${FREQ} MHz / ${TEMP}°C"
