#!/bin/bash

COUNT="$(task status:pending count)"

if [[ "$(task status:active count)" -gt 0 ]]; then
	COLOR="#40FF40"
elif [[ "$(task priority:H status:pending count)" -gt 0 ]]; then
	COLOR="#FF4040"
else
	COLOR="#808080"
fi

echo "$COUNT"
echo "$COUNT"
echo "$COLOR"
