#!/bin/bash

# Get number of pending tasks
COUNT="$(task status:pending count)"

if [[ "$COUNT" -ne 0 ]]; then
	# Save number of tasks for short_text content
	SHORTCOUNT=$COUNT
	# Get number of due tasks
	DUETASKS="$(task +DUE status:pending count)"

	# Change color and text according to due and high priority tasks
	if [[ "$DUETASKS" -gt 0 ]]; then
		COUNT="$DUETASKS! ($COUNT)"
		SHORTCOUNT="$DUETASKS"
		COLOR="#FF4040"
	elif [[ "$(task priority:H status:pending count)" -gt 0 ]]; then
		COUNT="$COUNT!"
		COLOR="#FFFFFF"
	else
		COLOR="#808080"
	fi

	# Finally, if a task is currently active, change color to green
	if [[ "$(task +ACTIVE count)" -gt 0 ]]; then
		COLOR="#40FF40"
	fi

	echo "$COUNT"
	echo "$SHORTCOUNT"
	echo "$COLOR"
else
	printf "\n\n\n"
fi
