#!/bin/bash

# Get number of pending tasks
COUNT="$(task status:pending count)"
SHORTCOUNT=$COUNT

# Get number of due tasks
DUETASKS="$(task due.before:7day status:pending count)"

if [[ "$(task status:active count)" -gt 0 ]]; then
	COLOR="#40FF40"
elif [[ "$(task priority:H status:pending count)" -gt 0 ]] || [[ "$DUETASKS" -gt 0 ]]; then
	COUNT="$DUETASKS! ($COUNT)"
	SHORTCOUNT="$DUETASKS"
	COLOR="#FF4040"
else
	COLOR="#808080"
fi

if [[ $COUNT -ne 0 ]]; then
	echo "$COUNT"
	echo "$SHORTCOUNT"
	echo "$COLOR"
else
	printf "\n\n\n"
fi
