#!/bin/sh
# ponymix-block - PulseAudio volume status for i3blocks using ponymix
# Written by Renan Guilherme <japareaggae@gmail.com>
# Released under the public domain <http://unlicense.org/UNLICENSE>

if ! ( which ponymix > /dev/null )
then
	echo "ponymix not installed?"
	echo "?"
	echo "#808080"
fi

# Perform actions when clicked
case $BLOCK_BUTTON in
	"1") ponymix toggle > /dev/null ;;
	"3") pavucontrol ;;
	"4") ponymix increase 5 > /dev/null ;;
	"5") ponymix decrease 5 > /dev/null ;;
esac

# Save the cycles!
VOLUME=$(ponymix get-volume)
DEVICE=$(ponymix | sed -n '2p' -)
case $DEVICE in
		*"Headset"*) DEFSINK="Headset";;
		*"HDMI"*) DEFSINK="HDMI";;
		*"Analog"*) DEFSINK="Analog";;
		*) DEFSINK="Unknown";;
esac

if ( ponymix is-muted ); then
	echo "$DEFSINK - $VOLUME% (M)"
	echo "$VOLUME"
	echo "#FF4040"
else
	echo "$DEFSINK - $VOLUME%"
	echo "$VOLUME"
	echo "#40FFFF"
fi

