#!/bin/sh
# ~/.i3/autostart - i3 autostart script
# While you can autostart things using .i3/config, I thought it would be a better
# idea to use a specific file to do these things.

# Desktop session - so dmenu-session knows who we are
export DESKTOP_SESSION="i3"

# LXPolkit - So we can mount Terezi from Thunar
/usr/lib/lxpolkit/lxpolkit &

# GNOME Keyring - For nm-applet, possibly others
gnome-keyring-daemon --start --components=secrets &

# Dropbox - File sync
dropboxd &

# NetworkManager - Because I don't trust dmenu-network just yet
nm-applet &

# xfce4-power-manager - Brightness keys only work when it's running
xfce4-power-manager &

# Clipit - Clipboard manager
clipit &

# Compton - vsync
(sleep 1s && compton) &

# MPD - Music Player Daemon
mpd &

# mpdscribble - Scrobbler for MPD
mpdscribble &

# PulseAudio Oneshooter - Starts PulseAudio and friends
~/.bin/pulseaudio-oneshot &

# XRandR Adjuster - Set up dual monitors
(sleep 2s && ~/.bin/xrandr-adjust) &

# fehbg - Wallpaper
(sleep 4s && ~/.fehbg) &

